### ISSUE TITLE
How to debug Ruby foreman project?

### ISSUE THREAD

**Issue by mozgbrasil** [Richard-Burd/react-redux-sandbox#12]
If you can help

-

As per images

https://drive.google.com/file/d/1GvQfJhf8WSbvIKecCLCpKcN3hglqs0pQ/view?usp=sharing

I created in the workspace some releases

The IDE starts the application, until I show the return in chrome

The problem is that the variable pointed at the breakpoint is not being returned

Can anyone help?

-

As per images

https://drive.google.com/file/d/1M6mhdvItbj2cu0Zqool6D5VZzhJHpM72/view?usp=sharing

The IDE starts the application, until I show the return in chrome

The problem is that the error is being returned when trying to debug the application

Can anyone help?

-

**Comment by Richard-Burd** [comment]
The README.md in this repo is incorrect because this repo does not have a Rails API back-end and the README.md must be updated to reflect this situation.

If you are interested in seeing a repo (with correct an accurate README.md) that has a working Rails-API back-end paired with a React-Redux front-end, see this repo [here](https://github.com/Richard-Burd/react-redux-portfolio-project). And also some notes [here](https://richard-burd.github.io/react_setup_with_rails_api_server) on how to create this setup from scratch.
